# Generated by Django 3.1.3 on 2020-11-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mwanafunziapp', '0002_auto_20201112_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageUrl',
        ),
    ]
